<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class HostRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findMACs()
    {
        $macs = [];

        $result =  $this->createQueryBuilder('h')
            ->select('h.mac')
            ->getQuery()
            ->getResult();

        foreach ($result as $item) {
            $macs[] = reset($item);
        }

        return $macs;
    }
}
